"""Trend analysis dimension loader for prompt enrichment.

Loads pre-extracted analytical dimensions from trend_knowledge/dimensions.json
and formats them for injection into Scope and Supervisor prompts.
Generated by notebooks/6_trend_skill.ipynb — do not edit directly.
"""

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

_CACHE: list[dict] | None = None


def _find_dimensions_file() -> Path | None:
    """Locate trend_knowledge/dimensions.json relative to the repo root."""
    candidates = [
        # Installed package: src/deep_research_from_scratch/ → repo root is 3 levels up
        Path(__file__).resolve().parent.parent.parent / "trend_knowledge" / "dimensions.json",
        # Running from repo root (e.g., notebooks or scripts)
        Path.cwd() / "trend_knowledge" / "dimensions.json",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def load_trend_dimensions() -> list[dict] | None:
    """Load trend analysis dimensions from the pre-generated knowledge file.

    Returns a list of dimension dicts on success, or None if the file is not
    found. Result is cached in memory to avoid repeated disk reads.
    """
    global _CACHE
    if _CACHE is not None:
        return _CACHE

    path = _find_dimensions_file()
    if path is None:
        logger.warning(
            "trend_knowledge/dimensions.json not found. "
            "Run notebooks/6_trend_skill.ipynb to generate it. "
            "Continuing without trend dimension guidance."
        )
        return None

    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        _CACHE = data.get("dimensions", [])
        logger.info("Loaded %d trend dimensions from %s", len(_CACHE), path)
        return _CACHE
    except Exception as e:
        logger.warning("Failed to load trend dimensions: %s", e)
        return None


def format_dimensions_for_prompt(dimensions: list[dict] | None) -> str:
    """Format trend dimensions as a compact Markdown list for prompt injection.

    Args:
        dimensions: List of dimension dicts from load_trend_dimensions(), or None.

    Returns:
        Formatted Markdown string, or empty string if dimensions is None/empty.
    """
    if not dimensions:
        return ""

    lines = []
    for d in dimensions:
        name = d.get("name", "")
        description = d.get("description", "")
        examples = d.get("examples", [])
        example_str = ", ".join(examples) if examples else ""
        line = f"- **{name}**: {description}"
        if example_str:
            line += f" (e.g., {example_str})"
        lines.append(line)

    return "\n".join(lines)
